version: '3.7'

services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"    # HTTP API
      - "6334:6334"    # GRPC API (opcional)
    volumes:
      - ./qdrant_data:/qdrant/storage  # Usa una ruta relativa para simplificar
    environment:
      - QDRANT_ALLOW_CORS=true    # Habilitar CORS para acceso web
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/readiness"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  qdrant_data:
    driver: local 